import { config } from '@vue/test-utils';
import { createI18n } from 'vue-i18n';

// Create a mock i18n instance for tests
const i18n = createI18n({
  legacy: false,
  locale: 'en',
  fallbackLocale: 'en',
  messages: {
    en: {
      // Basic translations for tests
      'career.swot.keyInsights': 'Key Insights',
      'career.swot.recommendations': 'Recommendations',
      'career.swot.actionItems': 'Action Items',
      'career.swot.priority.high': 'High',
      'career.swot.status.pending': 'Pending',
      'career.swot.deadline': 'Deadline',
      'career.learning.approach': 'Learning Approach',
      'career.learning.parallelLearning': 'Parallel Learning',
      'career.learning.tracks.architecture': 'Architecture',
      'career.learning.tracks.architectureDesc': 'Frontend Architecture',
      'career.learning.tracks.performance': 'Performance',
      'career.learning.tracks.performanceDesc': 'Performance Optimization',
      'career.learning.tracks.engineering': 'Engineering',
      'career.learning.tracks.engineeringDesc': 'Engineering Excellence',
      'career.learning.phaseTimeline': 'Phase Timeline',
      'career.learning.focus.architecture': 'Architecture Focus',
      'career.learning.learningGoals': 'Learning Goals',
      'career.learning.successCriteria': 'Success Criteria',
      'career.learning.practicalProjects': 'Practical Projects',
      'career.learning.difficulty.intermediate': 'Intermediate',
      'career.learning.expectedOutputs': 'Expected Outputs',
      'career.learning.recommendedResources': 'Recommended Resources',
      'career.learning.resources.books': 'Books',
      'career.learning.resources.courses': 'Courses',
      'career.learning.resources.practices': 'Practices',
      'career.learning.successMetrics': 'Success Metrics',
      'career.learning.metrics.technical': 'Technical Metrics',
      'career.learning.metrics.technicalItems.architecture': 'Architecture Skills',
      'career.learning.metrics.technicalItems.performance': 'Performance Skills',
      'career.learning.metrics.technicalItems.engineering': 'Engineering Skills',
      'career.learning.metrics.career': 'Career Metrics',
      'career.learning.metrics.careerItems.position': 'Position',
      'career.learning.metrics.careerItems.salary': 'Salary',
      'career.learning.metrics.careerItems.recognition': 'Recognition',
      'career.learning.metrics.impact': 'Impact Metrics',
      'career.learning.metrics.impactItems.team': 'Team Impact',
      'career.learning.metrics.impactItems.projects': 'Project Impact',
      'career.learning.metrics.impactItems.industry': 'Industry Impact',
      'career.roadmap.title': 'Career Roadmap',
      'career.roadmap.description': 'Career Development Plan',
      'career.roadmap.currentPhase': 'Current Phase',
      'career.roadmap.progress': 'Progress',
      'career.roadmap.milestones': 'Milestones',
      'career.roadmap.objectives': 'Objectives',
      'career.roadmap.deliverables': 'Deliverables',
      'career.roadmap.timeline': 'Timeline',
      'career.roadmap.status.notStarted': 'Not Started',
      'career.roadmap.status.inProgress': 'In Progress',
      'career.roadmap.status.completed': 'Completed',
      'career.roadmap.priority.high': 'High',
      'career.roadmap.priority.medium': 'Medium',
      'career.roadmap.priority.low': 'Low',
      // Contact form translations
      'contact.title': 'Contact Me',
      'contact.description': 'Welcome to contact me, I will reply to your message as soon as possible.',
      'contact.name': 'Name',
      'contact.email': 'Email',
      'contact.subject': 'Subject',
      'contact.category': 'Category',
      'contact.message': 'Message',
      'contact.required': 'Required',
      'contact.namePlaceholder': 'Please enter your name',
      'contact.emailPlaceholder': 'Please enter your email address',
      'contact.subjectPlaceholder': 'Please enter email subject',
      'contact.messagePlaceholder': 'Please enter your message content...',
      'contact.selectCategory': 'Please select contact category',
      'contact.categories.business': 'Business',
      'contact.categories.collaboration': 'Collaboration',
      'contact.categories.general': 'General',
      'contact.categories.feedback': 'Feedback',
      'contact.categories.other': 'Other',
      'contact.messageHelp': 'Please describe your needs or questions in detail, this will help me provide better assistance.',
      'contact.privacyAgreement': 'I agree to the',
      'contact.privacyPolicy': 'Privacy Policy',
      'contact.privacyAgreementSuffix': 'and allow processing of my personal information',
      'contact.privacyRequired': 'Please agree to the privacy policy',
      'contact.send': 'Send Message',
      'contact.sending': 'Sending...',
      'contact.validationError': 'Form validation failed',
      'contact.validationErrorMessage': 'Please check and correct the errors in the form',
      'contact.submitSuccess': 'Message sent successfully',
      'contact.submitSuccessMessage': 'Thank you for contacting me! I will reply to your message as soon as possible.',
      'contact.submitError': 'Send failed',
      'contact.submitErrorMessage': 'Sorry, message sending failed. Please try again later or use other contact methods.',
      'contact.alternativeContact': 'Alternative Contact Methods',
      'contact.emailDirect': 'Send email directly',
      'contact.responseTime': 'Usually reply within 24 hours',
      'errors.validation.required': 'This field is required',
      'errors.validation.email': 'Please enter a valid email address',
      'errors.validation.minLength': 'Minimum length is {min} characters',
      'errors.validation.maxLength': 'Maximum length is {max} characters',
      'common.reset': 'Reset'
    },
    zh: {
      // Chinese translations for tests
      'career.swot.keyInsights': '关键洞察',
      'career.swot.recommendations': '建议',
      'career.swot.actionItems': '行动项',
      'career.swot.priority.high': '高',
      'career.swot.status.pending': '待处理',
      'career.swot.deadline': '截止日期',
      'career.learning.approach': '学习方法',
      'career.learning.parallelLearning': '并行学习',
      'career.learning.tracks.architecture': '架构',
      'career.learning.tracks.architectureDesc': '前端架构',
      'career.learning.tracks.performance': '性能',
      'career.learning.tracks.performanceDesc': '性能优化',
      'career.learning.tracks.engineering': '工程化',
      'career.learning.tracks.engineeringDesc': '工程化卓越',
      'career.learning.phaseTimeline': '阶段时间线',
      'career.learning.focus.architecture': '架构重点',
      'career.learning.learningGoals': '学习目标',
      'career.learning.successCriteria': '成功标准',
      'career.learning.practicalProjects': '实践项目',
      'career.learning.difficulty.intermediate': '中级',
      'career.learning.expectedOutputs': '预期产出',
      'career.learning.recommendedResources': '推荐资源',
      'career.learning.resources.books': '书籍',
      'career.learning.resources.courses': '课程',
      'career.learning.resources.practices': '实践',
      'career.learning.successMetrics': '成功指标',
      'career.learning.metrics.technical': '技术指标',
      'career.learning.metrics.technicalItems.architecture': '架构技能',
      'career.learning.metrics.technicalItems.performance': '性能技能',
      'career.learning.metrics.technicalItems.engineering': '工程技能',
      'career.learning.metrics.career': '职业指标',
      'career.learning.metrics.careerItems.position': '职位',
      'career.learning.metrics.careerItems.salary': '薪资',
      'career.learning.metrics.careerItems.recognition': '认可度',
      'career.learning.metrics.impact': '影响力指标',
      'career.learning.metrics.impactItems.team': '团队影响',
      'career.learning.metrics.impactItems.projects': '项目影响',
      'career.learning.metrics.impactItems.industry': '行业影响',
      'career.roadmap.title': '职业路线图',
      'career.roadmap.description': '职业发展计划',
      'career.roadmap.currentPhase': '当前阶段',
      'career.roadmap.progress': '进度',
      'career.roadmap.milestones': '里程碑',
      'career.roadmap.objectives': '目标',
      'career.roadmap.deliverables': '交付物',
      'career.roadmap.timeline': '时间线',
      'career.roadmap.status.notStarted': '未开始',
      'career.roadmap.status.inProgress': '进行中',
      'career.roadmap.status.completed': '已完成',
      'career.roadmap.priority.high': '高',
      'career.roadmap.priority.medium': '中',
      'career.roadmap.priority.low': '低',
      // Contact form translations (Chinese)
      'contact.title': '联系我',
      'contact.description': '欢迎与我联系，我会尽快回复您的消息。',
      'contact.name': '姓名',
      'contact.email': '邮箱',
      'contact.subject': '主题',
      'contact.category': '类别',
      'contact.message': '消息',
      'contact.required': '必填',
      'contact.namePlaceholder': '请输入您的姓名',
      'contact.emailPlaceholder': '请输入您的邮箱地址',
      'contact.subjectPlaceholder': '请输入邮件主题',
      'contact.messagePlaceholder': '请输入您的消息内容...',
      'contact.selectCategory': '请选择联系类别',
      'contact.categories.business': '商务合作',
      'contact.categories.collaboration': '项目合作',
      'contact.categories.general': '一般咨询',
      'contact.categories.feedback': '反馈建议',
      'contact.categories.other': '其他',
      'contact.messageHelp': '请详细描述您的需求或问题，这将帮助我更好地为您提供帮助。',
      'contact.privacyAgreement': '我同意',
      'contact.privacyPolicy': '隐私政策',
      'contact.privacyAgreementSuffix': '并允许处理我的个人信息',
      'contact.privacyRequired': '请同意隐私政策',
      'contact.send': '发送消息',
      'contact.sending': '发送中...',
      'contact.validationError': '表单验证失败',
      'contact.validationErrorMessage': '请检查并修正表单中的错误',
      'contact.submitSuccess': '消息发送成功',
      'contact.submitSuccessMessage': '感谢您的联系！我会尽快回复您的消息。',
      'contact.submitError': '发送失败',
      'contact.submitErrorMessage': '抱歉，消息发送失败。请稍后重试或使用其他联系方式。',
      'contact.alternativeContact': '其他联系方式',
      'contact.emailDirect': '直接发送邮件',
      'contact.responseTime': '通常在24小时内回复',
      'errors.validation.required': '此字段为必填项',
      'errors.validation.email': '请输入有效的邮箱地址',
      'errors.validation.minLength': '最少需要{min}个字符',
      'errors.validation.maxLength': '最多允许{max}个字符',
      'common.reset': '重置'
    }
  }
});

// Configure Vue Test Utils to use the i18n instance
config.global.plugins = [i18n];